### ISSUE TITLE
Create Project Wireframe

### ISSUE THREAD

**Issue by Mike2481** [matthewpetriella/fluffy-potato#1]
Create wireframe for the project outlining landing page layout, dashboard page, and user-creation page

**Comment by matthewpetriella** [comment]
![main](https://user-images.githubusercontent.com/93597207/157143801-899cf460-5c30-4d20-a577-f6b3fe8a1169.jpeg)
![Click Into](https://user-images.githubusercontent.com/93597207/157143809-cd3474e5-40ae-40a4-a743-1a292c2e9ee2.jpeg)
